-- Seed Data: Common Vehicle Problems
-- Description: Populates the vehicle_problems table with common automotive issues
-- This data serves as the problem library for diagnostic tasks

-- Engine-related problems
INSERT INTO vehicle_problems (part_category, problem_name, symptoms, description, severity, common_causes, estimated_repair_cost, estimated_repair_time, created_by)
VALUES 
('Engine', 'Check Engine Light', 
  '["Light is illuminated on dashboard", "No immediate performance issues", "May indicate pending fault"]',
  'Check engine light (CEL) is triggered by the engine control module (ECM) when it detects exhaust system or fuel system problems',
  'Moderate',
  '["Faulty oxygen sensor", "Loose gas cap", "Damaged catalytic converter", "Spark plug issues"]',
  '150-500',
  '1-3 hours',
  'Admin'),

('Engine', 'Engine Knock/Ping',
  '["Metallic pinging sound during acceleration", "Sound increases under load", "More pronounced when using low-octane fuel"]',
  'Pre-ignition or detonation where fuel ignites before proper ignition timing in one or more cylinders',
  'Moderate',
  '["Low octane fuel", "Carbon buildup", "Faulty knock sensor", "Advanced ignition timing"]',
  '300-1200',
  '2-4 hours',
  'Admin'),

('Engine', 'Engine Overheating',
  '["Temperature gauge shows hot", "Steam from engine bay", "Loss of coolant", "Strong coolant smell"]',
  'Engine temperature exceeds normal operating range (usually above 220°F), causing potential engine damage',
  'Critical',
  '["Low coolant level", "Thermostat failure", "Water pump failure", "Clogged radiator", "Failed cooling fan"]',
  '500-2000',
  '3-6 hours',
  'Admin'),

('Engine', 'Loss of Power',
  '["Reduced acceleration", "Difficulty climbing hills", "Engine feels sluggish", "Lower fuel efficiency"]',
  'Engine does not produce normal horsepower or torque output',
  'Moderate',
  '["Clogged air filter", "Fuel injector issues", "Transmission slipping", "Faulty spark plugs", "Fuel pump failure"]',
  '200-1500',
  '2-5 hours',
  'Admin'),

-- Transmission-related problems
('Transmission', 'Hard Shifting',
  '["Jerky gear changes", "Delay between gears", "Clunking sound when shifting", "RPM flare on downshift"]',
  'Transmission has difficulty selecting or engaging proper gears, resulting in abrupt or delayed shifts',
  'Moderate',
  '["Low transmission fluid", "Worn transmission bands", "Faulty solenoid", "Transmission control module issue"]',
  '400-2500',
  '2-8 hours',
  'Admin'),

('Transmission', 'Transmission Slipping',
  '["Engine RPM increases without speed increase", "Loss of power", "Difficulty maintaining speed on hills", "Burning smell"]',
  'Transmission loses grip on power transfer, causing engine to over-rev relative to vehicle speed',
  'Critical',
  '["Low transmission fluid", "Worn clutch", "Transmission seal leak", "Faulty torque converter"]',
  '1000-4000',
  '4-10 hours',
  'Admin'),

('Transmission', 'Transmission Fluid Leak',
  '["Red fluid under vehicle", "Burning transmission fluid smell", "Transmission temperature warning"]',
  'Transmission fluid escapes through seals, gaskets, or pan',
  'Moderate',
  '["Worn seals", "Cracked transmission pan", "Loose bolts", "Transmission line rupture"]',
  '150-800',
  '1-3 hours',
  'Admin'),

-- Brake system problems
('Brakes', 'Brake Pad Wear',
  '["Brake warning light", "Longer stopping distance", "Grinding or squealing sound", "Soft brake pedal"]',
  'Friction material on brake pads has worn beyond safe operating thickness',
  'Moderate',
  '["Normal wear over time", "Aggressive driving", "Faulty caliper", "Contaminated brake fluid"]',
  '200-600',
  '1-2 hours',
  'Admin'),

('Brakes', 'Brake Fluid Leak',
  '["Soft or mushy brake pedal", "Brake pedal sinks to floor", "Brake warning light", "Fluid under vehicle"]',
  'Brake fluid escapes from hydraulic system components',
  'Critical',
  '["Worn brake line", "Faulty wheel cylinder", "Leaky caliper", "Master cylinder failure"]',
  '300-1200',
  '1-4 hours',
  'Admin'),

('Brakes', 'Brake Pulling/Uneven Braking',
  '["Vehicle pulls to one side when braking", "Uneven brake pad wear", "Reduced stopping power"]',
  'Braking force is not evenly distributed, causing vehicle to veer left or right',
  'Moderate',
  '["Sticky caliper", "Blocked brake line", "Uneven brake pad wear", "Contaminated brake fluid"]',
  '250-900',
  '2-3 hours',
  'Admin'),

-- Suspension-related problems
('Suspension', 'Worn Shocks/Struts',
  '["Bumpy ride", "Excessive bouncing", "Nose dives when braking", "Poor handling", "Uneven tire wear"]',
  'Shock absorbers or struts have lost ability to dampen suspension movement',
  'Moderate',
  '["Time and mileage", "Heavy loads", "Rough road conditions", "Suspension damage"]',
  '600-1200',
  '2-3 hours',
  'Admin'),

('Suspension', 'Broken Spring',
  '["Vehicle sags on one side", "Clunking sound from suspension", "Loss of ground clearance on one side"]',
  'Coil, leaf, or air suspension spring has fractured or separated',
  'Moderate',
  '["Age and corrosion", "Impact damage", "Heavy loads", "Worn suspension components"]',
  '400-1000',
  '2-4 hours',
  'Admin'),

('Suspension', 'Alignment Issues',
  '["Vehicle pulls to one side", "Uneven tire wear", "Steering wheel is off-center", "Poor handling"]',
  'Wheels are not properly aligned relative to vehicle frame and specifications',
  'Minor',
  '["Pothole impact", "Curb strike", "Suspension wear", "Worn steering components"]',
  '100-300',
  '1-2 hours',
  'Admin'),

-- Electrical system problems
('Electrical', 'Battery Dead/Weak',
  '["Slow engine cranking", "Dim lights", "Click sound when turning key", "Battery warning light"]',
  'Battery is unable to provide sufficient power for vehicle systems',
  'Moderate',
  '["Old battery", "Weak charging system", "Parasitic drain", "Cold weather"]',
  '100-300',
  '0.5-1 hour',
  'Admin'),

('Electrical', 'Alternator Failure',
  '["Battery warning light", "Dim lights while driving", "Electrical system warning", "Battery drains quickly"]',
  'Alternator fails to generate electrical power to charge battery and power electrical systems',
  'Critical',
  '["Worn alternator brushes", "Failed diode bridge", "Serpentine belt issue", "Electrical short"]',
  '400-1000',
  '1-3 hours',
  'Admin'),

('Electrical', 'Starter Motor Failure',
  '["Engine will not crank", "Single loud click on ignition", "No sound when turning key"]',
  'Starter motor cannot turn engine to begin combustion cycle',
  'Critical',
  '["Worn brushes", "Failed solenoid", "Weak battery", "Damaged flywheel ring gear"]',
  '300-800',
  '1-2 hours',
  'Admin'),

-- Cooling system problems
('Cooling', 'Coolant Leak',
  '["Green or orange fluid under vehicle", "Low coolant warning", "Overheating engine", "Sweet smell"]',
  'Coolant escapes from radiator, hoses, or heater core',
  'Moderate',
  '["Cracked radiator", "Failed water pump", "Corroded hose", "Loose connection"]',
  '150-600',
  '1-3 hours',
  'Admin'),

('Cooling', 'Thermostat Malfunction',
  '["Engine overheating or running too cool", "Fluctuating temperature gauge", "No heat from heater"]',
  'Thermostat fails to regulate engine coolant temperature',
  'Moderate',
  '["Age and wear", "Coolant contamination", "Failed thermostat valve", "Sensor issue"]',
  '200-500',
  '1-2 hours',
  'Admin'),

-- Exhaust system problems
('Exhaust', 'Exhaust Leak',
  '["Loud noise from under vehicle", "Burning smell", "Reduced fuel economy", "Rough idle"]',
  'Exhaust gases escape before reaching muffler',
  'Minor',
  '["Rusted exhaust pipe", "Loose manifold bolts", "Cracked manifold", "Failed gasket"]',
  '150-600',
  '1-3 hours',
  'Admin'),

('Exhaust', 'Damaged Catalytic Converter',
  '["Check engine light", "Loss of power", "Rotten egg smell", "Overheating converter"]',
  'Catalytic converter substrate is clogged, melted, or internally damaged',
  'Critical',
  '["Running too rich", "Spark plug misfire", "Oil contamination", "Thermal damage"]',
  '800-3000',
  '2-4 hours',
  'Admin'),

-- Tire and wheel problems
('Tires', 'Uneven Tire Wear',
  '["Tires worn on edges or center", "Vibration during driving", "Poor handling", "Reduced traction"]',
  'Tire tread wears unevenly across the surface',
  'Minor',
  '["Improper alignment", "Under/over inflation", "Worn suspension", "Aggressive driving"]',
  '0-200',
  '0.5-1 hour',
  'Admin'),

('Tires', 'Flat Tire',
  '["Sudden loss of pressure", "Bulge or bubble in tire", "Vehicle pulls to one side", "Flat warning light"]',
  'Tire loses air pressure due to puncture or seal failure',
  'Minor',
  '["Puncture from object", "Valve stem leak", "Bead leak", "Sidewall damage"]',
  '20-200',
  '0.5-1 hour',
  'Admin'),

-- Interior/Comfort problems
('Interior', 'Air Conditioning Not Cold',
  '["Blower works but no cold air", "Warm air from vents", "AC service needed"]',
  'Air conditioning system fails to produce cool air',
  'Minor',
  '["Low refrigerant", "Compressor failure", "Clogged condenser", "Faulty expansion valve"]',
  '300-1500',
  '2-4 hours',
  'Admin'),

('Interior', 'Power Window Failure',
  '["Window will not roll up or down", "Slow operation", "Grinding sound"]',
  'Power window motor or regulator fails to operate properly',
  'Minor',
  '["Failed motor", "Broken regulator", "Electrical issue", "Track obstruction"]',
  '150-500',
  '1-2 hours',
  'Admin'),

-- Exterior problems
('Exterior', 'Cracked Windshield',
  '["Visible crack or chip", "Impaired visibility", "Water leak"]',
  'Windshield glass is damaged and may compromise structural integrity',
  'Minor',
  '["Impact damage", "Temperature change", "Debris strike", "Road hazard"]',
  '200-600',
  '1-4 hours',
  'Admin'),

('Exterior', 'Rust and Corrosion',
  '["Visible rust on body panels", "Corrosion on undercarriage", "Paint damage"]',
  'Metal components oxidize and deteriorate',
  'Minor',
  '["Age and weather", "Road salt", "Moisture exposure", "Damaged paint"]',
  '200-2000',
  '2-8 hours',
  'Admin');

-- Log completion
SELECT 'Diagnostic problem library seeded successfully' AS status;
